### ISSUE TITLE
lxml import: undefined symbol: PyExc_BaseException

### ISSUE THREAD

**Issue by ubmarco** [m42e/arxml.vim#2]
Hello,
I wanna try out the plugin. However I have issues to get lxml working with the vim plugin.
When starting `vim` I get this exception:
```
Error detected while processing /home/marco/.vim_runtime/my_plugins/arxml.vim/plugin/arxml.vim:
line   38:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/marco/.vim_runtime/my_plugins/arxml.vim/plugin/../python/main.py", line 12, in <module>
    import vim_adaptor
  File "/home/marco/.vim_runtime/my_plugins/arxml.vim/python/vim_adaptor.py", line 11, in <module>
    from arxml_vim import xpath as x
  File "/home/marco/.vim_runtime/my_plugins/arxml.vim/python/arxml_vim/xpath.py", line 4, in <module>
    from lxml import etree
ImportError: /home/marco/.local/lib/python2.7/site-packages/lxml/etree.so: undefined symbol: PyExc_BaseException
```
I tried to install lxml in py2 and py3 locally and system wide. Always the same issue.
I also think there is a bug in arxml.vim which confused me first:
```
  if has('python3')
    let g:arxml_vim_python = 'py3'
  endif
  if has('python')
    let g:arxml_vim_python = 'py'
  endif
```
It will always use python2 not python3, because `arxml_vim_python` gets overwritten. That's why, at the beginning, it did not see my python3 lxml at all. After fixing it to
```
  if has('python3')
    let g:arxml_vim_python = 'py3'
  elseif has('python')
    let g:arxml_vim_python = 'py'
  endif
```
I got above exception. Don't know how to handle this. Any clues?
I'm on Manjaro 64bit.

**Comment by ubmarco** [comment]
By the way, running python2 or python3 from the terminal and doing 
`import lxml` or `from lxml import etree` works perfectly fine.

**Comment by ubmarco** [comment]
Hmm, maybe `vim` was compiled with Python3.6 support but I'm running Python3.7. For py3, vim always wants to run py37 not py36. I have both installed.

**Comment by m42e** [comment]
You could try:

´´´
:py3 import sys; print(sys.version)
´´´
To see what version is beeing used. And then check if this version has lxml installed.

**Comment by ubmarco** [comment]
Thanks for the quick reply. When running
```
:py3 import sys; print(f'Python version: {sys.version}'); import lxml; print(f'lxml import: {lxml}')
```
I get
```
Python version: 3.7.4 (default, Jul 16 2019, 07:12:58) 
[GCC 9.1.0]
lxml import: <module 'lxml' from '/usr/lib/python3.7/site-packages/lxml/__init__.py'>
```
However when I run
```
:py3 import sys; print(f'Python version: {sys.version}'); import lxml.etree
```
I get
```
Python version: 3.7.4 (default, Jul 16 2019, 07:12:58) 
[GCC 9.1.0]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/lib/python3.7/site-packages/lxml/etree.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_ImportError
```
The page http://vimdoc.sourceforge.net/htmldoc/if_pyth.html#python-dynamic tells for my case:

> When Python 2 and Python 3 are both supported they must be loaded dynamically.
> 
> When doing this on Linux/Unix systems and importing global symbols, this leads
> to a crash when the second Python version is used.  So either global symbols
> are loaded but only one Python version is activated, or no global symbols are
> loaded. The latter makes Python's "import" fail on libraries that expect the
> symbols to be provided by Vim.
> 
> Here Vim's behavior depends on the system in which it was configured.  In a
> system where both versions of Python were configured with --enable-shared,
> both versions of Python will be activated at the same time.  There will still
> be problems with other third party libraries that were not linked to
> libPython.

This looks relevant to my problem.

**Comment by m42e** [comment]
You could have a look if libxml2 and libxslt are installed?

**Comment by ubmarco** [comment]
Yes, both are there; actually I can run the following:
```
 marco@tux01 ~ python3.7
Python 3.7.4 (default, Jul 16 2019, 07:12:58) 
[GCC 9.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lxml.etree
>>> 
```
So on console everything works as expected, it's just in vim the symbols are not there.

**Comment by m42e** [comment]
hmmm, sorry, ¯\_(ツ)_/¯ I don't have a clue.

**Comment by m42e** [comment]
If py3 works, than python3 has been loaded. this is exclusively. But I'm really wondering why it does not use the same lib. 

a dirty hack, but you may call pip from within vim to install lxml?

```
:py3 -m pip install lxml
```

**Comment by ubmarco** [comment]
The command `:py3 -m pip install lxml` did not work because `:py3` expects Python code, it cannot be used for CLI arguments. I also tried `:py3file` but did not help due to problems with the `sys.argv` argument passing.
After all I think this has something to do with how vim supplies dynamically loaded global symbols from shared objects. In this case it's `/usr/lib/libpython3.7m.so.1.0` which supplies the symbols needed:
```
marco@tux01 ~ nm -D /usr/lib/libpython3.7m.so.1.0 | grep PyExc_ImportError
0000000000312f90 D PyExc_ImportError
```
while the lxml shared object file knows it but declares it as undefined
```
marco@tux01 ~ nm -D /usr/lib/python3.7/site-packages/lxml/etree.cpython-37m-x86_64-linux-gnu.so | grep PyExc_ImportError
                 U PyExc_ImportError
```
So I guess vim has to load libpython3.7m.so.1.0 and provide the symbols. My instance of vim is compiled with dynamic python2 / python3 support:
```
marco@tux01 ~ vim --version | grep python
+cmdline_hist      +langmap           +python/dyn        +visual
+cmdline_info      +libcall           +python3/dyn       +visualextra
```
I tried to recompile vim with just python3 support but I failed due to issues in the check-phase of the package build :/
Then I installed neovim using my existing vim configuration and the Python package `pynvim` for the neovim Python extension.
The arxml.vim plugin worked out-of-the-box. So I guess it's really about how vim provides the global symbols.

The bug I see seems to have nothing to do with this vim plugin, the PR can be closed.
Thanks for your time. Do you accept PRs for this package?

**Comment by m42e** [comment]
@ubmarco of course, feel free to improve it. I only use time to time.
